[feat][pat] add Add Folder button and modal
wormwithnoname/Snippets.io pull request #16
Opened 2021-08-09 08:56 UTC by PatTumulak

**What this PR does:**
- added an Add Folder button
- added an Add Folder modal

**Screenshots: **
![Screen Shot 2021-08-09 at 2 30 33 PM](https://user-images.githubusercontent.com/45306217/128681758-d89392cd-1299-42d1-9eec-e606f7f13578.png)
![Screen Shot 2021-08-09 at 4 55 00 PM](https://user-images.githubusercontent.com/45306217/128681766-76872650-45c5-4884-ab89-e8924e7c3e5e.png)

2021-08-09 10:03 UTC, itskichaem requested changes

2021-08-09 10:03 UTC, itskichaem commented on src/components/AddFolderButton/index.jsx
> +  const [isAddFolderModalVisible, setIsAddFolderModalVisible] = useState(false);
lets simplify this to `isModalVisible`

2021-08-09 10:03 UTC, itskichaem commented on src/components/AddFolderModal/index.jsx
> +function AddFolderModal({ handleCancel, isModalVisible }) {
event function props should be named `on-`. on this case this should be `onCancel`

2021-08-09 10:03 UTC, itskichaem commented on src/components/AddFolderButton/index.jsx
> +        handleCancel={() => setIsAddFolderModalVisible(false)}
lets avoid inlining functions. there should be a `handleCloseModal`  fn that does this.

2021-08-09 10:03 UTC, itskichaem commented on src/components/AddFolderButton/index.jsx
> +        onClick={() => setIsAddFolderModalVisible(true)}
lets avoid inlining functions. there should be a `handleOpenModal`  fn that does this.

2021-08-09 14:00 UTC, AnthonyDelaCruz requested changes

2021-08-09 14:00 UTC, AnthonyDelaCruz commented on src/components/AddFolderModal/styles.scss
> +    color: #fff;
use reusable colors

2021-08-09 14:00 UTC, AnthonyDelaCruz commented on src/components/AddFolderModal/index.jsx
> +      footer={null}
if it's null we can just omit the prop altogether.

2021-08-09 14:00 UTC, AnthonyDelaCruz commented on src/components/AddFolderModal/index.jsx
> +      destroyOnClose="true"
I think you are passing the wrong prop type here for `destroyClose`, the Modal API in the docs says it accepts a boolean not a string, but I understand the intention, also If the prop is always true, we don't have to explicitly pass `true` as a value. We can just place the prop `destroyOnClose` without assigning a value. This means that it's always true.

2021-08-10 08:20 UTC, itskichaem approved these changes

2021-08-10 08:21 UTC, merged